
package co.edureka.hibernate.orm;

/**
 * BookTags generated by hbm2java
 */
public class BookTags implements java.io.Serializable {

	private Integer idbookTags;
	private String idbooks;
	private String tagValue;
	private String tagType;

	public BookTags() {
	}

	public BookTags(String idbooks, String tagValue, String tagType) {
		this.idbooks = idbooks;
		this.tagValue = tagValue;
		this.tagType = tagType;
	}

	public Integer getIdbookTags() {
		return this.idbookTags;
	}

	public void setIdbookTags(Integer idbookTags) {
		this.idbookTags = idbookTags;
	}

	public String getIdbooks() {
		return this.idbooks;
	}

	public void setIdbooks(String idbooks) {
		this.idbooks = idbooks;
	}

	public String getTagValue() {
		return this.tagValue;
	}

	public void setTagValue(String tagValue) {
		this.tagValue = tagValue;
	}

	public String getTagType() {
		return this.tagType;
	}

	public void setTagType(String tagType) {
		this.tagType = tagType;
	}

}
