package co.edureka.hibernate.orm;

/**
 * TagTypes generated by hbm2java
 */
public class TagTypes implements java.io.Serializable {


	private static final long serialVersionUID = 3476832973048259823L;
	private Integer idtagTypes;
	private String tagTypeName;

	public TagTypes() {
	}

	public TagTypes(String tagTypeName) {
		this.tagTypeName = tagTypeName;
	}

	public Integer getIdtagTypes() {
		return this.idtagTypes;
	}

	public void setIdtagTypes(Integer idtagTypes) {
		this.idtagTypes = idtagTypes;
	}

	public String getTagTypeName() {
		return this.tagTypeName;
	}

	public void setTagTypeName(String tagTypeName) {
		this.tagTypeName = tagTypeName;
	}

}
